os:
  - linux
  - osx
osx_image: xcode11.2
dist: trusty
language: generic
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swiftenv install $(cat .swift-version) | grep -qe "\(been\|already\) installed"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swift package generate-xcodeproj --enable-code-coverage; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait swift test; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project ConfigParser.xcodeproj -scheme ConfigParser-Package build test; fi
after_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash <(curl -s https://codecov.io/bash) -J 'ConfigParser'; fi
